## Numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
b = np.array([[1,2,3,4],[5,4,6,7],[9,10,11,12]])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b

array([[ 1,  2,  3,  4],
       [ 5,  4,  6,  7],
       [ 9, 10, 11, 12]])

In [7]:
b[0]

array([1, 2, 3, 4])

In [8]:
b[1]

array([5, 4, 6, 7])

In [10]:
b[2]

array([ 9, 10, 11, 12])

### creating and array of zeros

In [12]:
a = np.zeros(2)

In [13]:
a

array([0., 0.])

In [14]:
a = np.zeros(3)

In [15]:
a

array([0., 0., 0.])

In [17]:
a = np.zeros(4)

In [36]:
a

array([0., 0.])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating array with ones

In [19]:
b = np.ones(3)

In [40]:
b

array([1., 1., 1.])

In [42]:
np.ones((2,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

#### Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [25]:
# create an empty array with 2 elements
a = np.empty(2)

In [26]:
a

array([0., 0.])

In [45]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

##### You can create an array with a range of elements: 

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

##### And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and step size.


In [30]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:


In [47]:
np.linspace(2,10, 6)   # 6 numbers from 2 to 10 you can also directly right 6 for can also use num = 6 for mentioning the steps

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [33]:
np.linspace(2.2,20.4,num=6)

array([ 2.2 ,  5.84,  9.48, 13.12, 16.76, 20.4 ])

In [34]:
np.linspace(2.2,20.4,num=6,endpoint=False)

array([ 2.2       ,  5.23333333,  8.26666667, 11.3       , 14.33333333,
       17.36666667])

In [35]:
# it gives sample and the step it takes mentioned outside the output
np.linspace(5,10,num=3,retstep=True)

(array([ 5. ,  7.5, 10. ]), 2.5)

#### Specifying your data type

while the default type is floating point (np.float64), you can explicitly specify which data type you wnat using the dtype keyword.