## Numpy

In [10]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])

In [4]:
b = np.array([[1,2,3,4],[5,4,6,7],[9,10,11,12]])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
b

array([[ 1,  2,  3,  4],
       [ 5,  4,  6,  7],
       [ 9, 10, 11, 12]])

In [7]:
b[0]

array([1, 2, 3, 4])

In [8]:
b[1]

array([5, 4, 6, 7])

In [10]:
b[2]

array([ 9, 10, 11, 12])

### creating and array of zeros

In [12]:
a = np.zeros(2)

In [13]:
a

array([0., 0.])

In [14]:
a = np.zeros(3)

In [15]:
a

array([0., 0., 0.])

In [17]:
a = np.zeros(4)

In [36]:
a

array([0., 0.])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creating array with ones

In [19]:
b = np.ones(3)

In [40]:
b

array([1., 1., 1.])

In [42]:
np.ones((2,3),dtype = int)

array([[1, 1, 1],
       [1, 1, 1]])

#### Or even an empty array! The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

In [25]:
# create an empty array with 2 elements
a = np.empty(2)

In [26]:
a

array([0., 0.])

In [45]:
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

##### You can create an array with a range of elements: 

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

##### And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and step size.


In [30]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

##### You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:


In [47]:
np.linspace(2,10, 6)   # 6 numbers from 2 to 10 you can also directly right 6 for can also use num = 6 for mentioning the steps

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [33]:
np.linspace(2.2,20.4,num=6)

array([ 2.2 ,  5.84,  9.48, 13.12, 16.76, 20.4 ])

In [11]:
np.linspace(2.2,20.4,num=6,endpoint=False)

array([ 2.2       ,  5.23333333,  8.26666667, 11.3       , 14.33333333,
       17.36666667])

In [14]:
# it gives sample and the step it takes mentioned outside the output
np.linspace(5,10,num=3,retstep=True)

(array([ 5. ,  7.5, 10. ]), 2.5)

#### Specifying your data type

while the default type is floating point (np.float64), you can explicitly specify which data type you wnat using the dtype keyword.

In [13]:
np.ones(2, dtype= np.int64)

array([1, 1], dtype=int64)

In [15]:
np.ones((2,3),dtype= int)

array([[1, 1, 1],
       [1, 1, 1]])

## Adding, removing, and sorting elements 

Sorting an element is simple with np.sort(). You can specify the axis, kind, and order when you call the function.

If you start with this array:


In [16]:
a = np.array([2,3,1,4,5,7,9,8,])
np.sort(a)

array([1, 2, 3, 4, 5, 7, 8, 9])

Adding arrays

In [32]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# You can concatenate them with np.concatenate()

np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [35]:
x  = np.array([[1,2],[3,4]])
y = np.array([[5,6]]) # this is 2 dimensional array with double brackets
# you can concatenate them with 

np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

#### How do you know the shape and size of an array ?

1. ndarray.ndim will tell you the number of axes, or dimensions, of the array.

2. ndarraay.size will tell you the total number of elemets of the array. This is the product of elements of the array's shape

3. ndarray.shape will display a tuple of integers that indicate number of elements stored along each dimension of the array. If, for example, you have 2-D array with 2 rows and 3 columns, the shape of your array is (2,3).

In [36]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [37]:
array_example.ndim

3

In [38]:
array_example.size

24

In [39]:
array_example.shape

(3, 2, 4)

#### Can you reshape an array?

Yes!

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [52]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [53]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### How to convert a 1D array into a 2D array (how to add a new axis to an array)

You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [54]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [55]:
a1 = a[np.newaxis, :]
a1.shape

(1, 6)

In [56]:
a1


array([[1, 2, 3, 4, 5, 6]])

In [57]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [58]:
col_vector = a[:,np.newaxis]
col_vector.shape

(6, 1)

In [59]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

You can use np.expand_dims to add an axis at index position 1 with:


In [61]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [62]:
c = np.expand_dims(a, axis=0 )
c.shape

(1, 6)

#### Indexing and slicing

In [63]:
data = np.array([1,2,3])

data[1]

2

In [64]:
data[0:2]

array([1, 2])

In [65]:
data[1:]

array([2, 3])

In [67]:
data[-2:]

array([2, 3])

In [68]:
data[:-2]

array([1])