In [1]:
import numpy as np

In [4]:
# Creation of numpy array and python list

arr = np.array([1,2,3,4])
b = [1,2,3,4]

print(type(arr))
print(type(b))

<class 'numpy.ndarray'>
<class 'list'>


In [9]:
# addition 
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

sum = a + b
print("sum: ",sum)

#dot product
product = np.dot(a,b)
print("product: ", product)

sum:  [ 6  8 10 12]
product:  70


In [12]:
np.full((3,3), 10)

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Types of Array and it's Creation

There are two main General Mechanism of creating arrays.<br>

**1. Converting Python Sequences to NumPy Arrays :** <br>
NumPy arrays can be created from various Python sequences, such as lists and tuples, where python lists are defined using square brackets eg [1, 2, 3, 4] and parentheses for tuples eg (1, 2, 3, 4). <br>
These sequences can be used to create NumPy ndarrays with different dimensions.<br><br>
Any array object created using NumPy is referred to as an ndarray, where the "nd" stands for "n-dimensional." <br>
This terminology is used to differentiate NumPy arrays from standard Python sequences such as lists and tuples.<br><br>
**2. Array Creation Function :**<br>
Numpy provides several functions for creating arrays with specific values or patterns<br>
**1) np.zeros :** creates an array filled with zeros<br>
**2) np.ones :** creates an array filled with ones<br>
**3) np.empty :** creates an array without initializing its values (i.e., the values are uninitialized and may contain random data)<br>
**4) np.arange :** creates an array with evenly spaced values within a specified interval<br>
**5) np.linspace :** creates an array with a specified number of evenly spaced values within a specified interval<br>
**6) np.logspace :** creates an array with a specified number of logarithmically spaced values within a specified interval<br>
**7) np.full() :** creates an array of specified shape and fills it with a specified value.<br>
**8) np.eye() :** creates an identity matrix, which is a square matrix with ones on the diagonal and zeros elsewhere<br>

In [19]:
#converting python list to numpy array

list1 = [1,2,3,4]
arr1 = np.array(list1)
print(arr1)

#converting python tuple to numpy array

tuple1 = (1,2,3,4)
arr2 = np.array(tuple1)
print(arr2)

# creating 2d array
arr3 = np.array([[1,2],[3,4]])
print(arr3)

arr4 = np.array([[[5,6],[7,8]],[[9,10],[11,12]]])
print(arr4)

[1 2 3 4]
[1 2 3 4]
[[1 2]
 [3 4]]
[[[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [21]:
# creating multidimentional array using numpy function

arr5 = np.arange(2,21,2)
arr5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
np.linspace(3,9,5)

array([3. , 4.5, 6. , 7.5, 9. ])

In [23]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [25]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.empty([3,3],dtype=int)

array([[          0,           0, -1086465648],
       [        583, -1086465200,         583],
       [-1086465840,         583,  1752440934]])

In [28]:
# degree to radians

trig = np.array([30,45,60,90])

radian = np.deg2rad(trig)
radian

array([0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [29]:
sin = np.sin(trig)
cos = np.cos(trig)

print(sin)
print(cos)

[-0.98803162  0.85090352 -0.30481062  0.89399666]
[ 0.15425145  0.52532199 -0.95241298 -0.44807362]


In [35]:
# agreegation function

a = np.array([1,2,3,4,5])
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.std(a))
print(np.amax(a))
print(np.amin(a))

print(np.mean(a))
print(np.median(a))

1
5
15
1.4142135623730951
5
1
3.0
3.0


In [36]:
b = np.array([3,4,2,6,9,23,13])
np.sort(b)

array([ 2,  3,  4,  6,  9, 13, 23])

In [38]:
(np.sort(b)[::-1])

array([23, 13,  9,  6,  4,  3,  2])

In [39]:
# indexing

a = np.array([1,2,3,4,5,6])
a[3]

4

In [41]:
a[1]

2

In [42]:
# sclicing

a[2:4]

array([3, 4])

In [48]:
a[2::2]

array([3, 5])

In [44]:
a[-1]

6

In [46]:
b = np.array([[1,2],[3,4]])
b[0][1]

2

In [47]:
b[1][1]

4